server:
    port: 8080

spring:
    application:
        name: user-service

eureka:
    instance:
        instance-id: ${spring.application.name}:${server.port}
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
