server:
    port: 8090

spring:
    application:
        name: order-service

eureka:
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
    client:
        service-url:
            defaultZone: http://localhost:9800/eureka/
